### ISSUE TITLE
[mingw-w64-make] Is it possible to bring back Guile support?

### ISSUE THREAD

**Issue by mbakhterev** [Alexpux/MINGW-packages#3298]
It is much more easier and efficient to automate complex build processes with embedded Guile procedures than with GNU Make's own internal language. Is it possible to enable Guile support again?

**Comment by irakhlin** [comment]
I don't believe that guile currently builds for mingw64 due to a long standing issue with the guile package itself. https://github.com/Alexpux/MINGW-packages/issues/699

**Comment by Alexpux** [comment]
@irakhlin try to build both 32 and 64 yourself

**Comment by vzh** [comment]
Hi there,
There was reported on the guile-user mailing list that the following branch should work:
http://git.savannah.gnu.org/cgit/guile.git/log/?h=wip-mingw-guile-2.2
There are several patches for MinGW there.

**Comment by Alexpux** [comment]
@vzh I will not build package from git, only release versions

**Comment by vzh** [comment]
OK, thank you! I'll ask guile devs if they have any plans on releasing it.

**Comment by spk121** [comment]
@vzh @Alexpux Yeah, that mingw guile git branch is mine, so I suppose it is up to me to see if I can get those patches past the maintainers and into mainline.  I'll see what I can do.

**Comment by gjanssens** [comment]
@spk121 Have you made some progress in mainlining your patches ? It would really be helpful to have a mingw guile package.

**Comment by spk121** [comment]
The upcoming 3.0.6 release should support MinGW out of the box at least at some level. The unthreaded, 32-bit build will definitely work, though it won't pass the test suite 100% due to missing features. We're hoping to get the 64-bit build and the threaded build fixed by 3.0.6 as well, but, it is TBD.

**Comment by alex-tee** [comment]
Guile 3.0.7 is out. is it possible to re-add guile support with this release?

**Comment by Biswa96** [comment]
Are we asking for mingw-w64-guile package here? Or somehow adding guile in make 😕

**Comment by alex-tee** [comment]
I personally just want libguile (so a mingw-w64-guile package), but the guile base package is also stuck at version 2 and could use an update (if possible)

**Comment by jcalve** [comment]
I tried to compile 3.0.7, master, and a branch named "wip-mingw", the furthest I got was on the later with `./configure --enable-mini-gmp --disable-networking` but it still fails after a while...

**Comment by Biswa96** [comment]
I have sent an email in guile mailing list here https://lists.gnu.org/archive/html/guile-devel/2022-10/msg00019.html. If things go well I can try to add mingw-w64-guile package.

**Comment by Biswa96** [comment]
Some updates.

1. With `gethostname()`, the build fails with the error:
```
ld.exe: .libs/libguile_3.0_la-posix.o: in function `scm_gethostname':
libguile/posix.c:2379: undefined reference to '__imp_gethostname_used_without_requesting_gnulib_module_gethostname'
```
Some info about that in here https://lists.gnu.org/archive/html/bug-gnulib/2010-09/msg00265.html

2. If I disable the `gethostname()` check with this diff

```diff
--- a/configure.ac
+++ b/configure.ac
@@ -565,7 +565,7 @@ AC_CHECK_DECLS([_NL_NUMERIC_GROUPING], [], [], [[#include <langinfo.h>]])
 #       only with `_XOPEN_SOURCE' or some such.
 #
 AC_CHECK_HEADERS([crypt.h netdb.h pthread.h pthread_np.h sys/param.h sys/resource.h sys/file.h sys/mman.h])
-AC_CHECK_FUNCS(chroot flock getlogin cuserid getpriority setpriority getpass sethostname gethostname)
+AC_CHECK_FUNCS(chroot flock getlogin cuserid getpriority setpriority getpass sethostname)
 AC_CHECK_DECLS([sethostname, hstrerror, cuserid])
 
 # crypt() may or may not be available, for instance in some countries there
```
guile.exe itself fails with the errors
* with lto:
```
Mingw-w64 runtime failure:
32 bit pseudo relocation at 00007FF721B21584 out of range, targeting 00007FFECD4B7690, yielding the value 00000007AB996108.
```

* without lto:
```
Pre-boot error; key: misc-error, args: ("primitive-load-path" "Unable to find file ~S in load path" ("ice-9/boot-9") #f)
```

**Comment by mmuetzel** [comment]
For the first error, you might need to add `gethostname` to the list of gnulib modules (`gl_MODULES`) in `m4/gnulib-cache.m4`. After that, you might need to run `autogen.sh` to regenerate the files.

**Comment by Biswa96** [comment]
I have tried that but same build error with gethostname.

**Comment by mmuetzel** [comment]
Sorry. That was a bit more involved than I initially thought.
I regenerated the gnulib files including the `gethostname` module from the same commit they used to get their gnulib files the last time. (First patch.)
With that, compilation failed pretty early on because of a missing header. (Second patch.)
But it still doesn't work for me.

Just wanted to share the patches in case you are more successful:
[guile-patches.zip](https://github.com/msys2/MINGW-packages/files/9768168/guile-patches.zip)

**Comment by spk121** [comment]
Hi. The only version of Guile that I've built successfully on MinGW recently is MSys2 MinGW 32.
From the latest commit in the 'main' branch of the upstream repo, the configure line that works is
./configure CFLAGS="-g -Wall -O1" --enable-lto=no --without-threads --enable-jit=no --enable-mini-gmp -C

So it is 32-bit only, unthreaded.

The 64-bit build remains broken because of long == 4 bytes, when guile expects long == 8 bytes.  There are some patches, but, nothing moved into the main tree

**Comment by Kreijstal** [comment]
someone has done CI with mingw64 here https://github.com/lyrra/guile

**Comment by Kreijstal** [comment]
Hi, I took a look, and I can build it albeit with some errors. 

If anyone wants to take a look come and help!

https://github.com/lyrra/guile/pull/3

**Comment by jcalve** [comment]
Looks like there's a new attempt at fixing mingw64 builds:

http://git.savannah.gnu.org/cgit/guile.git/log/?h=wip-mingw-2025

Some discussion in the mailing list:

https://lists.gnu.org/archive/html/guile-devel/2025-03/threads.html
