### ISSUE TITLE
qtcreator: QbsProjectManager4.dll: The specified procedure could not be found.

### ISSUE THREAD

**Issue by askondro** [Alexpux/MINGW-packages#3317]
After starting qtcreator a plugin loader dialog appears and shows the error: 

> "C:\msys64\mingw64\lib\qtcreator\plugins\QbsProjectManager4.dll: Cannot load library C:\msys64\mingw64\lib\qtcreator\plugins\QbsProjectManager4.dll: The specified procedure could not be found."

Other than that, qtcreator seems to work fine..

**Comment by olerapx** [comment]
Can confirm that error on two different machines using Windows 10. Qt Creator works just fine after disabling the module

**Comment by kelteseth** [comment]
Same here :)

**Comment by ninepillars** [comment]
me too...
But I clone the whole sources and build it myself, replace the QbsProjectManager4.dll, then the problem is resolved.

**Comment by xylosper** [comment]
Same here. No problem when built it by myself using same PKGBUILD in the repository.

**Comment by kelteseth** [comment]
I think this issue can be closed. The latest Qt/QBS/QtCreator update fixed this issue for me.

**Comment by askondro** [comment]
Can confirm that it works after the update. Closing.

**Comment by kelteseth** [comment]
After the last qt update this bug is back. Can anyone confirm?

**Comment by Alexpux** [comment]
This is due qbs update. Need qt creator rebuild. wait some days or downgrade qbs
