### ISSUE TITLE
feature request: gdb-git package

### ISSUE THREAD

**Issue by fracting** [Alexpux/MINGW-packages#862]
Hi @mingwandroid 

Could you provide a gdb-git PKGBUILD, so I can test latest gdb on both Windows and Wine?
(I'm planing to test on https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=shortlog;h=refs/heads/users/palves/mingw-cxx-conversion actually)

Thanks!

**Comment by mingwandroid** [comment]
Sure thing. Doing it now.

**Comment by mingwandroid** [comment]
Hi @fracting, I've committed this now. It uses the branch you requested. I didn't get a chance to test it yet unfortunately, but it should be OK.

**Comment by mingwandroid** [comment]
.. please close this issue if it works for you.

**Comment by fracting** [comment]
Thanks @mingwandroid !

I tested on Windows XP but got this error when building:

config.status: executing depfiles commands
rm -f c-exp.c c-exp.c.tmp
/bin/sh ../../gdb/gdb/../ylwrap ../../gdb/gdb/c-exp.y y.tab.c c-exp.c -- bison -y  && mv c-exp.c c-exp.c.tmp \
        || (rm -f c-exp.c; false)
/home/Administrator/MINGW-packages/mingw-w64-gdb-git.bak/src/build-i686-w64-mingw32/gdb/../../gdb/gdb/c-exp.y: 警告: 39 shift/reduce conflicts [-Wconflicts-sr]
/home/Administrator/MINGW-packages/mingw-w64-gdb-git.bak/src/build-i686-w64-mingw32/gdb/../../gdb/gdb/c-exp.y: 警告: 53 reduce/reduce conflicts [-Wconflicts-rr]
E:\msys32\mingw32\bin\m4.exe:E:/msys32/usr/share/bison/c-skel.m4:26: cannot open `/usr/share/bison/yacc.c': No such file or directory


(The Chinese word '警告' means 'warning')

Do you have idea what did I miss?

Thanks!

**Comment by mingwandroid** [comment]
It seems you have installed mingw-w64 i686 (i.e. native) m4.exe (E:\msys32\mingw32\bin\m4.exe) which doesn't understand msys2 paths. You need to remove that.

**Comment by fracting** [comment]
Good catch! I almost forgot I compiled and installed mingw-w64-i686-m4 by myself, now I understand why it isn't included in MSYS2 binary repo.

After removing native m4, gdb compiles fine.

As Pedro requested, I slightly change your PKGBUILD in order to compile gdb with --enable-build-with-cxx, it compiles fine, but reports "This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information." when debugging a simple hello world program. 

Before closing this issue, I'll rebuild gdb without build-with-cxx and see if I can reproduce, then decide where to report (upstream / here).

**Comment by mingwandroid** [comment]
Where is this discussion with Pedro taking place? IRC? What is the goal here?

Is this related to the binutils bug you had with xz? I also ran into that bug but I have not had time to track it down. You mentioned that the bug is fixed in binutils-git? I think we need to back-port the patch unless binutils are planning a new release sometime soon. Do you think it is possible to track down which commit fixed that problem?

Too many questions, apologies!

**Comment by fracting** [comment]
Sorry for didn't provide the link earlier ;-)

The discussion is here:
https://sourceware.org/ml/gdb-patches/2015-11/msg00049.html

I just see Pedro send some MINGW g++ fix to gdb-patches and he is seeking for testing, so I volunteer to test his patches.

This not related to the ld bug when linking xz. I'm still waiting Nick or anybody else to comment on that ld bug, or waiting myself to be free to tracking down a bit farther. (No, it is not fixed yet, otherwise I'm glad to do some reverse-regression test or anything else to figure out the commit)

**Comment by fracting** [comment]
update:

gdb works fine on Windows without build-with-cxx. I'll report back to Pedro.

**Comment by mingwandroid** [comment]
Interesting, I wonder if you can provide a backtrace for the failure? The PKGBUILD is building in debug mode without stripping debug information. If you install it to another --root you might be able to debug one gdb with the other :-)

Debugging debuggers is never much fun, I find myself getting confused.

**Comment by fracting** [comment]
I can reproduce this issue on Wine: gcc build works fine as on Windows, g++ build broken as on Windows.

However, there is no backtrace at exit, I tried start gdb using WineDbg, and it still doesn't print backtrace.

The exit status is 0x3, same on Windows and Wine.

**Comment by mingwandroid** [comment]
Running the broken gdb through the a working gdb, can you try:

    b mingw_onexit
    r
    bt

**Comment by fracting** [comment]
Thanks, that idea helps. I think it doesn't call mingw_onexit() according to my test result, instead it calls abort(). (abort() set exit status to 0x3 according to Wine source code, also google the error message show information about abort() as well: http://stackoverflow.com/questions/8177152/what-is-the-cause-of-this-application-has-requested-the-runtime-to-terminate-it )

```
Breakpoint 2, 0x00870778 in abort ()
(gdb) bt
#0  0x00870778 in abort ()
#1  0x0085ebda in uw_init_context_1 ()
#2  0x0085f2de in _Unwind_RaiseException ()
#3  0x008728e5 in __cxa_throw ()
#4  0x006cfead in throw_exception (exception=...)
    at ../../gdb/gdb/common/common-exceptions.c:295
#5  0x006d000d in throw_it (reason=RETURN_ERROR, error=GENERIC_ERROR,
    fmt=0x8d86bc <filename_display_kind_names+52> "No symbol table is loaded.  Use the \"file\" command.", ap=0x320f754 "~aP")
    at ../../gdb/gdb/common/common-exceptions.c:354
#6  0x006d0034 in throw_verror (error=GENERIC_ERROR,
    fmt=0x8d86bc <filename_display_kind_names+52> "No symbol table is loaded.  Use the \"file\" command.", ap=0x320f754 "~aP")
    at ../../gdb/gdb/common/common-exceptions.c:360
#7  0x0068c1f6 in verror (
    string=<error reading variable: Could not find the frame base for "verror(char const*, char*)".>,
    args=<error reading variable: Could not find the frame base for "verror(char const*, char*)".>) at ../../gdb/gdb/utils.c:525
#8  0x006cfc77 in error (
    fmt=0x8d86bc <filename_display_kind_names+52> "No symbol table is loaded.  Use the \"file\" command.") at ../../gdb/gdb/common/errors.c:43
#9  0x0050c964 in set_default_source_symtab_and_line ()
    at ../../gdb/gdb/source.c:207
#10 0x00474fa0 in list_command (
    arg=<error reading variable: Could not find the frame base for "list_command(char*, int)".>,
    from_tty=<error reading variable: Could not find the frame base for "list_command(char*, int)".>) at ../../gdb/gdb/cli/cli-cmds.c:912
#11 0x0046e5d8 in do_cfunc (c=0x2a74f0, args=0x0, from_tty=1)
    at ../../gdb/gdb/cli/cli-decode.c:105
#12 0x00470f36 in cmd_func (cmd=0x2a74f0, args=0x0, from_tty=1)
    at ../../gdb/gdb/cli/cli-decode.c:1885
#13 0x00689691 in execute_command (
    p=<error reading variable: Could not find the frame base for "execute_command(char*, int)".>,
    from_tty=<error reading variable: Could not find the frame base for "execute_command(char*, int)".>) at ../../gdb/gdb/top.c:475
#14 0x0058b170 in command_handler (command=0x2460f8 "l")
    at ../../gdb/gdb/event-top.c:492
#15 0x0058b66e in command_line_handler (rl=0x330bb68 "h\273\060\003")
    at ../../gdb/gdb/event-top.c:691
#16 0x0058b7df in gdb_readline2 (client_data=0x0)
    at ../../gdb/gdb/event-top.c:772
#17 0x0058b08b in stdin_event_handler (error=0, client_data=0x0)
    at ../../gdb/gdb/event-top.c:430
#18 0x0058a2de in handle_file_event (
    file_ptr=<error reading variable: Could not find the frame base for "handle_file_event(file_handler*, int)".>,
    ready_mask=<error reading variable: Could not find the frame base for "handle_file_event(file_handler*, int)".>) at ../../gdb/gdb/event-loop.c:708
#19 0x0058a52b in gdb_wait_for_event (
    block=<error reading variable: Could not find the frame base for "gdb_wait_for_event(int)".>) at ../../gdb/gdb/event-loop.c:859
#20 0x005899f0 in gdb_do_one_event () at ../../gdb/gdb/event-loop.c:323
#21 0x00589a23 in start_event_loop () at ../../gdb/gdb/event-loop.c:347
#22 0x0058acb4 in cli_command_loop (data=0x0) at ../../gdb/gdb/event-top.c:186
#23 0x0058223b in current_interp_command_loop ()
    at ../../gdb/gdb/interps.c:317
#24 0x00583504 in captured_command_loop (
    data=<error reading variable: Could not find the frame base for "captured_command_loop(void*)".>) at ../../gdb/gdb/main.c:318
#25 0x0057f5f2 in catch_errors (
    func=<error reading variable: Could not find the frame base for "catch_errors(int (*)(void*), void*, char*, return_mask)".>,
    func_args=<error reading variable: Could not find the frame base for "catch_errors(int (*)(void*), void*, char*, return_mask)".>,
    errstring=<error reading variable: Could not find the frame base for "catch_errors(int (*)(void*), void*, char*, return_mask)".>,
    mask=<error reading variable: Could not find the frame base for "catch_errors(int (*)(void*), void*, char*, return_mask)".>)
    at ../../gdb/gdb/exceptions.c:240
#26 0x00584929 in captured_main (
    data=<error reading variable: Could not find the frame base for "captured_main(void*)".>) at ../../gdb/gdb/main.c:1157
#27 0x0057f5f2 in catch_errors (
    func=<error reading variable: Could not find the frame base for "catch_errors(int (*)(void*), void*, char*, return_mask)".>,
    func_args=<error reading variable: Could not find the frame base for "catch_errors(int (*)(void*), void*, char*, return_mask)".>,
    errstring=<error reading variable: Could not find the frame base for "catch_errors(int (*)(void*), void*, char*, return_mask)".>,
    mask=<error reading variable: Could not find the frame base for "catch_errors(int (*)(void*), void*, char*, return_mask)".>)
    at ../../gdb/gdb/exceptions.c:240
#28 0x00584954 in gdb_main (
    args=<error reading variable: Could not find the frame base for "gdb_main(captured_main_args*)".>) at ../../gdb/gdb/main.c:1165
#29 0x00401698 in main (argc=1, argv=0x241338) at ../../gdb/gdb/gdb.c:32
```

**Comment by fracting** [comment]
Note that Pedro pushed an exception fix, as well as a printf fix: https://sourceware.org/ml/gdb-patches/2015-11/msg00116.html

But it doesn't fix the problem for me.

I built Pedro's branch with i686-w64-mingw32-g++ (4.9.2) cross-compiler from Ubuntu without MSYS2 patches, and it works fine.

It is possible related to gcc version?

**Comment by fracting** [comment]
Update:

After investigate further I found actually this patch fix the issue for MSYS2 mingw-w64 gdb.

I was testing the wrong binary due to frequently switch between
Windows VM and Linux host.
Sorry for the stupid mistake and noise.

@mingwandroid do you need to remove some patch from the patchset?

**Comment by mingwandroid** [comment]
I don't think we do? Or am I misunderstanding? Our patches don't do anything major by the look of it. One prevents a potential linker error and another some warnings.

I have a flu though so won't do any hacking until I am better..

**Comment by fracting** [comment]
@mingwandroid hey, take care! have a rest and see you later! ;-)
